# Generated by Django 5.2.8 on 2026-05-08 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('message_template', models.TextField(verbose_name='Message template')),
                ('sender_id', models.CharField(max_length=24, verbose_name='Sender ID')),
                ('send_method', models.CharField(choices=[('smpp', 'SMPP'), ('http', 'HTTP')], default='smpp', max_length=8, verbose_name='Send method')),
                ('user_uid', models.CharField(blank=True, default='', max_length=24, verbose_name='Jasmin user UID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='draft', max_length=12, verbose_name='Status')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('throttle_mps', models.PositiveIntegerField(default=10, verbose_name='Throttle (msgs/sec)')),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaigns_campaign',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(db_index=True, max_length=24, verbose_name='Phone number')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='Template variables')),
                ('msgid', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Jasmin message ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('undelivered', 'Undelivered'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=12, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Campaign recipient',
                'verbose_name_plural': 'Campaign recipients',
                'db_table': 'campaigns_recipient',
                'indexes': [models.Index(fields=['campaign', 'status'], name='campaigns_r_campaig_cbc617_idx'), models.Index(fields=['campaign', 'msgid'], name='campaigns_r_campaig_089a78_idx')],
            },
        ),
    ]
