# Generated by Django 5.2.8 on 2026-05-08 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(help_text='The sender ID as it appears on the handset, e.g. JASMIN, ACME-TX.', max_length=24, unique=True, verbose_name='Value')),
                ('label', models.CharField(blank=True, default='', help_text='Friendly description shown in the picker.', max_length=120, verbose_name='Label')),
                ('sms_type', models.CharField(blank=True, default='', help_text='Restrict to a specific SMS type, or leave blank for any.', max_length=16, verbose_name='Allowed SMS type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Sender ID',
                'verbose_name_plural': 'Sender IDs',
                'db_table': 'campaigns_senderid',
                'ordering': ('value',),
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='audience_source',
            field=models.CharField(choices=[('csv', 'CSV upload'), ('quick_list', 'Quick number list')], default='csv', max_length=16, verbose_name='Audience source'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='encoding',
            field=models.CharField(choices=[('auto', 'Auto-detect'), ('gsm7', 'GSM 7-bit'), ('ucs2', 'UCS-2 (Unicode)')], default='auto', max_length=8, verbose_name='Encoding'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_rtl',
            field=models.BooleanField(default=False, verbose_name='Right-to-left'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='message_validity',
            field=models.CharField(blank=True, choices=[('', 'Unlimited'), ('3600', '1 hour'), ('21600', '6 hours'), ('43200', '12 hours'), ('86400', '24 hours'), ('172800', '48 hours')], default='', max_length=12, verbose_name='Message validity (seconds)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sms_type',
            field=models.CharField(choices=[('transactional', 'Transactional'), ('promotional', 'Promotional'), ('otp', 'OTP'), ('marketing', 'Marketing')], default='transactional', max_length=16, verbose_name='SMS type'),
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('body', models.TextField(verbose_name='Message body')),
                ('sms_type', models.CharField(choices=[('transactional', 'Transactional'), ('promotional', 'Promotional'), ('otp', 'OTP'), ('marketing', 'Marketing')], default='transactional', max_length=16, verbose_name='SMS type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message template',
                'verbose_name_plural': 'Message templates',
                'db_table': 'campaigns_messagetemplate',
                'ordering': ('name',),
            },
        ),
    ]
